DROP DATABASE IF EXISTS `quotes_db`;
CREATE DATABASE `quotes_db`;

USE quotes_db;

CREATE TABLE quotes(
  id INTEGER AUTO_INCREMENT NOT NULL,
  mood VARCHAR(100),
  quote VARCHAR(2000),
  PRIMARY KEY (id)
);

